const reservatons = [
  {
    id: 1,
    src: "https://demoadmin.berighthere.com/image/TG002/DD1/Autonetic%20Spaces%205.jpg",
    name: "Dedicated Desk",
    duration: "1 Month",
    price: "Rs 8500",
    book: "Book Space",
  },
  {
    id: 2,
    src: "https://demoadmin.berighthere.com/image/TG002/MR8/MR.jpg",
    name: "Meeting Room - 8 Seater",
    duration: "1 Hour",
    price: "Rs 750",
    book: "Book Space",
  },
  {
    id: 3,
    src: "https://demoadmin.berighthere.com/image/TG002/CR35/CR.jpg",
    name: "Conference Room - 35 Seater",
    duration: "1 Hour",
    price: "Rs 600",
    book: "Book Space",
  },
  {
    id: 4,
    src: "https://demoadmin.berighthere.com/image/TG002/HD1/PC.png",
    name: "Flexi / Hot Desk",
    duration: "1 Month",
    price: "Rs 6000",
    book: "Book Space",
  },
  {
    id: 5,
    src: "https://demoadmin.berighthere.com/image/TG002/HD1/PC.png",
    name: "Private Cabin - 3 Seater",
    duration: "1 Month",
    price: "Rs 15000",
    book: "Book Space",
  },
  {
    id: 5,
    src: "https://demoadmin.berighthere.com/image/TG002/MGRM3/Autonetic%20Spaces%208.jpg",
    name: "Manager Room - 3 Seater",
    duration: "1 Month",
    price: "Rs 5000",
    book: "Book Space",
  },
  {
    id: 5,
    src: "https://demoadmin.berighthere.com/image/TG002/PC7/Autonetic%20Spaces%2011.jpg",
    name: "Private Cabin - 7 Seater",
    duration: "1 Month",
    price: "Rs 5000",
    book: "Book Space",
  },
];
export default reservatons;
